# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
- task: SqlAzureDacpacDeployment@1
  displayName: Execute Azure SQL
  inputs:
    azureSubscription: 'cc8b5566-0d2f-48b0-ba2c-2e5751b25a37'
    ServerName: 'pawsibile.database.windows.net'
    DatabaseName: 'Pawsible'
    SqlUsername: 'PawsibleApp'
    SqlPassword: 'AnythingIsPawsible123!'
    DacpacFile: '/pawsible-db/bin/Debug/Pawsible.dacpac'
